language: rust
rust: nightly
cache: cargo

branches:
  # don't re-run builds after semver tagging
  except:
    - /^v[0-9]+\.[0-9]+\.[0-9]+/

script:
  - |
      cargo build &&
      cargo test &&
      cargo bench

deploy:
  # deploy to crates
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script: scripts/deploy.sh
